# Generated by Django 5.2.7 on 2025-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0004_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_exiled',
            field=models.BooleanField(default=False),
        ),
    ]
