# Generated by Django 5.2.7 on 2025-11-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0004_seed_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='is_host',
        ),
    ]
