# Generated by Django 5.2.7 on 2025-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0005_gameuser_is_exiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='health_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
