# Generated by Django 5.2.7 on 2025-12-05 14:35

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0006_gameuser_health_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='avatars/'),
        ),
    ]
