# Generated by Django 5.2.7 on 2025-11-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0006_roomparticipant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomParticipant',
        ),
    ]
