# Generated by Django 5.2.7 on 2025-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunkerroom',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bunkerroom',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
