# Generated by Django 5.2.7 on 2025-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0007_delete_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
